setting:
  name: "rgb_r3live_incre_reg"
  output_root: "./experiments/"
  pc_path: "/home/cy/NeRF/shine_mapping_input/Map_pointcloud_wo_pose"
  image_path: "/home/cy/NeRF/shine_mapping_input/image/resized_rgb"
  label_path: "" # optional for semantic mapping
  pose_path: "/home/cy/NeRF/shine_mapping_input/Lidar_pose_kitti.txt"
  calib_path: ""
  load_model: False
  model_path: "" 
  first_frame_ref: False
  begin_frame: 0
  end_frame: 862
  every_frame: 1 # 1 means does not skip
  device: "cuda"
  gpu_id: "0"
camera:
  image_width: 1280
  image_height: 1024
  fx: 863.4241
  fy: 863.4171
  cx: 640.6808
  cy: 518.3392
  camera_ext_matrix: [-0.00113207, -0.0158688, 0.999873, 0.050166,
                      -0.9999999,  -0.000486594, -0.00113994, 0.0474116,
                      0.000504622,  -0.999874,  -0.0158682, -0.0312415,
                      0, 0, 0, 1]
  # camera_ext_matrix: [-0.00113207, -0.9999999, 0.000504622, 0, 
  #                     -0.0158688,  -0.000486594, -0.999874, 0,
  #                     0.999873,  -0.00113994,  -0.0158682, 0,
  #                     0, 0, 0, 1]
process:
  min_range_m: 1.5 # default: 3.0
  pc_radius_m: 50.0  # distance filter for each frame. Default value is 25.0
  min_z_m: -10.0 # defalut: -3.5
  rand_downsample: False # use random or voxel downsampling
  vox_down_m: 0.05
  rand_down_r: 0.2
sampler:
  surface_sample_range_m: 0.5 #default: 0.5
  surface_sample_n: 3
  free_sample_begin_ratio: 0.3 #default: 0.3
  free_sample_end_dist_m: 1.0 #default: 1.0
  free_sample_n: 3
octree:
  leaf_vox_size: 0.1 #default: 0.2
  tree_level_world: 12
  tree_level_feat: 3 # default: 3
  color_tree_level_feat: 3
  feature_dim: 32 # default: 8
  poly_int_on: True
  octree_from_surface_samples: True
  color_feature_dim: 32
  color_poly_int_on: True
decoder:
  mlp_level: 2
  mlp_hidden_dim: 32
  freeze_after_frame: 20
  color_mlp_level: 2
  color_mlp_hidden_dim: 32
loss:
  ray_loss: True
  main_loss_type: dr  # select from sdf_bce (our proposed), sdf_l1, sdf_l2, dr, dr_neus
  sigma_sigmoid_m: 0.1  # default: 0.1
  loss_weight_on: False
  behind_dropoff_on: False
  ekional_loss_on: False
  weight_e: 0.1
continual:
  continual_learning_reg: True # using incremental mapping with regularization. default: True. 注意关闭这个以后大于500帧时的too many scans, use cpu memory
  lambda_forget: 1e4 # the larger this value, the model would be less likely to forget. default: 1e4
  color_lambda_forget: 0
  window_replay_on: False # replay within the sliding window
  window_radius_m: 0
optimizer:
  iters: 50  # iterations per frame. default value is 50.
  batch_size: 4096
  learning_rate: 0.01
  calibration_lr: 0.00001
  weight_decay: 1e-7 # l2 regularization
eval:
  wandb_vis_on: True # log to wandb or not. default: False
  o3d_vis_on: True # visualize the mapping or not
  vis_freq_iters: 0 
  save_freq_iters: 861 # save the model and octree every x iterations
  save_freq_frame: 1000 # save the model and octree every x frames
  mesh_freq_frame: 5 # reconstruct the mesh every x frames
  mc_res_m: 0.05 # reconstruction marching cubes resolution. default: 0.1
  mc_with_octree: True # querying sdf only in certain levels of the octree
  mc_local: False
  mc_vis_level: 1 # default: 1
  save_map: True # save the sdf map or not. default: False

